// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import { KitErrorPayload } from "@pithy-sh/core/src/error/payload";
import type { ArgsDef, CommandDef } from "citty";
import { CATALOG } from "../capabilities/catalog";
import { HIDDEN_ROOT_FLAGS } from "../commands/alias";
import { main } from "../main";
import { ROOT_FLAGS } from "../rootFlags";

/**
 * What the kit contains, as one file another repository can read.
 *
 * `pithy.sh/docs` is 360 pages of hand-written reference and nothing verifies it. The site's own harness
 * (`marketing/scripts/check/run.mjs`) is where that verification goes — three questions, each answerable
 * only from here: does every `pithy add <name>` on a page name a real capability, does every flag a page
 * cites exist in that command's parser, and does every error code a page quotes exist in the kit.
 *
 * **The shape of the answer is a decision for this repository, and this is it.** The site's slug check
 * already asks the first question, and it asks it by reading `capabilities/catalog.ts` off an absolute
 * path and running a regular expression over the TypeScript. That has failed the way regular expressions
 * over source fail: the character class was `[a-z-]`, `i18n` has a digit in it, and the catalog entry
 * simply did not match — so `pithy add i18n` read as an unknown slug on every page that stated it. The
 * check carries a `names.length < 10` tripwire because a partial read is otherwise indistinguishable
 * from a complete one.
 *
 * So the export is generated from the values themselves — the catalog array, the composed citty tree,
 * the error union — and committed as strict JSON. A consumer parses it; there is no shape to guess at
 * and no partial read to detect.
 *
 * **JSON, not JSONC**, which is the one place this departs from the repository's config rule: the reader
 * is another repository's `JSON.parse`, and that tool does not recognize comments. The rationale lives
 * here, in the generator, which is where `docs/catalog.generated.json` sends anyone who opens it.
 */

/** Where the generated file lives, relative to the repository root. One string, so nothing spells it twice. */
export const CATALOG_PATH = "docs/catalog.generated.json";

/** The note the file opens with. See {@link DocsCatalog.$generated} for why it is a field and not a comment. */
const GENERATED_NOTE =
  "Generated by packages/cli/src/docs/writeCatalog.ts. Do not edit by hand; run `bun run docs-catalog`. " +
  "Strict JSON rather than JSONC because the reader is another repository's JSON.parse — see " +
  "packages/cli/src/docs/catalog.ts for what each section answers.";

/** One capability, as `pithy add` accepts it. */
export interface CatalogCapability {
  /** The `pithy add <name>` argument. */
  name: string;
  /** The npm package it ships in — `@pithy-sh/<name>` for all but `controlplane`, which ships inside core. */
  package: string;
}

/** One command in the tree: the path a caller types, and the flags its parser accepts. */
export interface CatalogCommand {
  /** Space-separated, from the root down — `add`, `token mint`. The root itself is not a command. */
  path: string;
  /** Every flag spelling the parser answers to: the long form, then any aliases. */
  flags: string[];
}

/** One error code the kit defines, and the HTTP status its member pins. */
export interface CatalogErrorCode {
  /** `domain/reason`, namespaced per capability. */
  code: string;
  /** The status the kit pins to this code. Every kit member pins exactly one. */
  status: number;
}

/**
 * Everything a docs check needs to know about the kit.
 *
 * **`commands` answers whether a flag exists on a command, not whether a page may name it.** A page
 * legitimately cites another command's flag — `docs/commands/deploy.md` writes `pithy provision --env
 * <name> --yes` while explaining what deploy refuses to do — and prose quotes flags belonging to
 * neither (`git rev-parse --git-common-dir`). So a consumer matches `<command> --flag` as a pair.
 * Attributing every flag on a page to that page's command reports correct pages as wrong, which is
 * worse than no check at all: one that cries wolf gets turned off.
 */
export interface DocsCatalog {
  /**
   * What this file is, for whoever opens it.
   *
   * A generated file says so at the top, and every other one this repository generates says it in a
   * comment. This one cannot: strict JSON has no comments, and the reason it is strict JSON is the
   * reader. So the note is a field. It is first because that is where a reader looks, and a consumer
   * that reads the sections by name never sees it.
   */
  $generated: string;
  capabilities: CatalogCapability[];
  commands: CatalogCommand[];
  /** Flags that work on any command, declared by no command — `bin.ts` answers them before citty parses. */
  globalFlags: string[];
  errorCodes: CatalogErrorCode[];
}

/**
 * Every flag the CLI parses outside a command's `args`, in every spelling.
 *
 * A walk of the command tree cannot find one of these: `bin.ts` answers all six before citty is handed
 * the arguments. So `pithy add --help` and `pithy --pithiest` both cite something real, and a check
 * reading only the parsers would call each a typo — on a page that is correct.
 *
 * **Composed from the modules that decide, never restated.** The two hidden flags were missed on the
 * first pass, and a literal list here would go stale the same way the moment a seventh landed: hidden
 * from `--help` is not hidden from a docs check, and nothing would have said so. `ROOT_FLAGS` and
 * `HIDDEN_ROOT_FLAGS` are exported for this, so a new out-of-band flag reaches the export with nothing
 * to remember.
 */
const GLOBAL_FLAGS: readonly string[] = [...ROOT_FLAGS, ...HIDDEN_ROOT_FLAGS];

/** One arg's declared aliases, in the spelling a caller types: a single letter takes one dash, a word takes two. */
function aliasFlags(alias: unknown): string[] {
  const names = typeof alias === "string" ? [alias] : Array.isArray(alias) ? alias : [];
  return names
    .filter((name): name is string => typeof name === "string")
    .map((name) => (name.length === 1 ? `-${name}` : `--${name}`));
}

/**
 * The camelCase spelling of a kebab-case arg name, or the name unchanged when it has no dash.
 *
 * citty registers `camelCase(name)` and `kebabCase(name)` as aliases of **every** arg it parses, so
 * `--withPrerequisites` reaches the same value as `--with-prerequisites`. This transform is narrow on
 * purpose — it handles lowercase kebab and nothing else — and `catalog.test.ts` holds every arg name in
 * the CLI to that shape, so the narrow version is complete rather than merely convenient. The kebab
 * direction is a no-op over that domain, which is why only this one exists.
 */
function camelSpelling(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

/**
 * Every flag one command's parser answers to.
 *
 * Three spellings beyond the declared name, each of them citty's rather than ours, and each one a false
 * failure for a docs check that does not know about it:
 *
 * - **Declared aliases**, long and short.
 * - **The camelCase form.** citty aliases every arg to its camel and kebab spellings, so
 *   `--withPrerequisites` works. The `flagsOf` doc used to claim citty does no case mapping. It does.
 * - **`--no-<name>` on a boolean.** citty strips a `--no-` prefix from any argument before parsing, and
 *   this CLI documents the result: `ui.ts`'s own description offers `--no-auth for the bare SPA`, and
 *   `docs/commands/ui.md` puts `[--auth | --no-auth]` in its synopsis. An export without it makes a
 *   deliberately-documented page read as citing a flag that does not exist — the cries-wolf failure this
 *   whole shape was chosen to avoid. Emitted for booleans only: citty would also answer `--no-env`, but
 *   naming that would be claiming a flag rather than reporting one.
 *
 * A **positional** is not a flag and is left out: it carries no `--`, so a check looking for one would
 * never ask about it.
 */
export function flagsOf(args: ArgsDef | undefined): string[] {
  const flags: string[] = [];
  for (const [name, def] of Object.entries(args ?? {})) {
    const arg = def as { type?: string; alias?: unknown };
    if (arg.type === "positional") continue;
    flags.push(`--${name}`);
    const camel = camelSpelling(name);
    if (camel !== name) flags.push(`--${camel}`);
    flags.push(...aliasFlags(arg.alias));
    if (arg.type === "boolean") flags.push(`--no-${name}`);
  }
  return flags;
}

/**
 * citty's `Resolvable<T>`: a value, a promise of one, or a thunk returning either.
 *
 * Both `subCommands` and `args` are declared this way, so one resolver covers both. Reading either
 * unawaited is silent rather than loud — `Object.entries` of a promise or a function is `[]`, so the
 * command reads as taking no flags and the group as having no children.
 */
type Resolvable<T> = T | Promise<T> | (() => T | Promise<T>);

/** One `Resolvable`, resolved. */
async function resolve<T>(value: Resolvable<T>): Promise<T> {
  return typeof value === "function" ? await (value as () => T | Promise<T>)() : await value;
}

/**
 * Every command under `root`, sorted by the path a caller types.
 *
 * Groups are walked **and listed**. `pithy token` takes no flags of its own, but a page that spells one
 * is still citing a command, and a list that skipped it would have nothing to say about that page.
 *
 * All three of citty's subcommand spellings are resolved. This CLI writes thunks so the tree stays lazy;
 * reading only the literal form would have found the root's twenty-six names and none of their flags.
 */
export async function walkCommands(root: CommandDef, prefix: string[] = []): Promise<CatalogCommand[]> {
  const found: CatalogCommand[] = [];
  // The container is a `Resolvable` as much as anything inside it, and this repository already builds the
  // lazy form: `dispatch.ts`'s `ownNamesOnly` returns `subCommands: async () => …`, and `bin.ts` wraps the
  // tree in it before dispatching. Reading it unawaited takes `Object.entries` of a function — no names,
  // no children, and a whole subtree missing from the export with nothing to say so, because the
  // non-empty guard is still satisfied by the commands that did resolve.
  const declared = root.subCommands === undefined ? {} : await resolve(root.subCommands);
  const subCommands = declared as Record<string, Resolvable<CommandDef>>;
  for (const [name, value] of Object.entries(subCommands)) {
    const child = await resolve(value);
    const path = [...prefix, name];
    found.push({
      path: path.join(" "),
      flags: flagsOf(child.args === undefined ? undefined : await resolve(child.args)),
    });
    found.push(...(await walkCommands(child, path)));
  }
  return found.sort((left, right) => left.path.localeCompare(right.path));
}

/**
 * The catalog, built from the values the kit runs on.
 *
 * Every section is asserted non-empty. Not a floor — a floor is a number somebody has to raise by hand,
 * and it is wrong the moment they do not — but the one state that can only mean the reader broke: a kit
 * with no capabilities, no commands or no error codes has never existed. A check running against an
 * empty section reports `ok` on every page, and that is the result worth refusing to write.
 */
export async function buildDocsCatalog(): Promise<DocsCatalog> {
  const catalog: DocsCatalog = {
    $generated: GENERATED_NOTE,
    capabilities: CATALOG.map((entry) => ({ name: entry.name, package: entry.package })).sort((left, right) =>
      left.name.localeCompare(right.name),
    ),
    commands: await walkCommands(main),
    globalFlags: [...GLOBAL_FLAGS].sort(),
    errorCodes: KitErrorPayload.options
      .map((member) => ({ code: member.shape.code.value, status: member.shape.status.value }))
      .sort((left, right) => left.code.localeCompare(right.code)),
  };
  for (const [section, entries] of Object.entries(catalog)) {
    if (Array.isArray(entries) && entries.length === 0) {
      throw new Error(`The docs catalog read no ${section}. Fix the reader before trusting it.`);
    }
  }
  return catalog;
}

/**
 * The exact bytes the catalog file should hold: two-space JSON, one trailing newline.
 *
 * `.generated.` is in the filename because Biome ignores that, and it has to: this expands every array
 * and Biome's JSON formatter fits short ones onto one line, so the writer and the formatter would each
 * undo the other on every run. See `biome.jsonc`.
 */
export function renderDocsCatalog(catalog: DocsCatalog): string {
  return `${JSON.stringify(catalog, null, 2)}\n`;
}
