// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import { migrateProject } from "../migrations/run";
import { loadProject, loadProjectCloudflare, requireProjectName } from "../project/config";
import { detectPackageManager, type InstallRunner } from "../project/packageManager";
import type { WorkerTarget } from "../project/workers";
import { seedProject } from "../seed/run";
import type { DevConfig } from "./devConfig";
import { syncFeatureDevConfig } from "./sync";
import { createWorktree, defaultGit, type GitRunner } from "./worktree";

/**
 * `pithy feature create` — the local, automatic half of the lifecycle, run from the main checkout. It
 * creates the branch + worktree (the proven core), reserves a non-overlapping port block and pins one port
 * per worker into the worktree's `.dev.config.json`, installs deps with the adopter's package manager, then
 * migrates and seeds the local Miniflare backend. No Cloudflare spend — a working local env, ready for
 * `pithy dev`, from one command.
 *
 * No `.dev.vars` is wired here, and none is copied. Each Worker's is generated by `pithy dev` from this
 * machine's own sources (#154), so a fresh worktree needs nothing carried into it.
 */

/** A local/dev backend step (migrate or seed) — a seam so create is testable without Miniflare. */
export type LocalRunner = (args: { projectDir: string }) => Promise<void>;

// A `dev` migrate names its project too: the local Miniflare store lives at the project root and is
// shared with `wrangler dev`, and this is usually the run that first stamps it. An unstamped database is
// one any project can later claim, so the first write is the only chance to record the owner.
const localMigrate: LocalRunner = async ({ projectDir }) => {
  // One config load, two facts: the name the database is stamped with, and the account it is reached in.
  // Both are read from the **worktree's** own `pithy.config.ts`, because the branch being created is what
  // decides them and it may already differ from the checkout this command was run in (#234).
  const config = await loadProject(projectDir);
  await migrateProject({
    env: "dev",
    projectDir,
    project: requireProjectName(config),
    account: loadProjectCloudflare(config) ?? null,
  });
};

// Even a `dev` seed names its project: Cloudflare Images and Stream have no local emulation, so a media
// fixture here writes into the same account-wide store production shares, and only the ownership metadata
// says who put it there.
const localSeed: LocalRunner = async ({ projectDir }) => {
  const config = await loadProject(projectDir);
  await seedProject({
    env: "dev",
    projectDir,
    project: requireProjectName(config),
    account: loadProjectCloudflare(config) ?? null,
    json: true,
  });
};

/**
 * The structured outcome of `pithy feature create` — the `--json` payload and the human summary source.
 *
 * **It says nothing about migrate and seed, and that is the change (#231).** It used to carry
 * `migrated: true, seeded: true`, both written as literals a few lines below the two `await`s. Neither
 * step has a flag here and both throw on failure, so a report that exists at all is the proof they ran:
 * the pair was a constant with the grammar of a fact, and the only branch a consumer could write on it
 * — `if (migrated && !seeded)` — is one that can never fire and can never be tested. If create ever
 * grows a `--skip-data` of its own, `feature sync`'s `data` is the field to copy, because a value that
 * can be `false` is the only kind worth emitting.
 */
export interface CreateReport {
  /** The command that produced the report. */
  command: "feature.create";
  /** The feature branch created or attached. */
  branch: string;
  /** The absolute worktree path. */
  worktree: string;
  /**
   * Whether a new worktree was created (false on an idempotent re-run over an existing one).
   *
   * **Named for what it created (#235).** It was `created`, and `pithy ui add` emits a `created` of its
   * own that is a `string[]` of files — one name, two types, so `if (result.created)` is true for a
   * non-empty file list and true for this boolean, and a consumer that guessed wrong got no error. The
   * subject is the outlier here: `ui`'s says *what* was created, this one says *whether*, and the thing it
   * says it about is already in the payload beside it. `feature.destroy` had settled the convention
   * anyway — `portsFreed`, `worktreePruned`, `branchDeleted` — so a bare `created` was the odd one out
   * inside its own command before it was one across the CLI.
   */
  worktreeCreated: boolean;
  /**
   * The ref the branch was cut from — the trunk's name, or `"HEAD"`. **Null when nothing was cut**: an
   * already-registered worktree, or a branch that already existed and was attached to.
   *
   * The command reports how far the trunk is behind its remote, and only when this is non-null. On the
   * attach path that sentence would be about a base somebody else chose months ago — a false sentence
   * about a base, which is the defect `#454` is about.
   */
  base: string | null;
  /** The feature's dev config — its reserved port block and each worker's pinned endpoint. */
  dev: DevConfig;
}

/** Options for {@link createFeature}. */
export interface CreateFeatureOptions {
  /** The main checkout root — the port registry's key, and where the source `.dev.vars` lives. */
  projectDir: string;
  /** The issue number. */
  issue: string;
  /** The kebab-case slug. */
  slug: string;
  /** Skip the dependency install (tests set this; a real run installs so the gates run in the tree). */
  skipInstall?: boolean;
  /** Ports per feature block (defaults to the registry's block size). */
  blockSize?: number;
  /** The registry file (default: `<config>/dev-ports.json`). A seam, so a test never writes the real one. */
  registryPath?: string;
  /** git runner seam. */
  git?: GitRunner;
  /** Install runner seam. */
  install?: InstallRunner;
  /** Local migrate seam (default: `migrateProject` against dev). */
  migrate?: LocalRunner;
  /** Local seed seam (default: `seedProject` against dev). */
  seed?: LocalRunner;
  /** Worker-discovery seam (default: `discoverWorkers`), so tests fix the worker set. */
  discoverWorkers?: (projectDir: string) => Promise<WorkerTarget[]>;
}

/**
 * Stand up a feature's local environment. Creates the worktree, reserves its port block and pins one port
 * per worker into `.dev.config.json`, installs deps (unless skipped),
 * then migrates and seeds the local backend. Idempotent: a re-run reuses the existing worktree, keeps its
 * port block (so every worker's address is stable for the life of the feature), and re-runs migrate/seed
 * harmlessly.
 */
export async function createFeature(options: CreateFeatureOptions): Promise<CreateReport> {
  const git = options.git ?? defaultGit;
  const worktree = await createWorktree({ issue: options.issue, slug: options.slug, git });

  // Install before discovering workers so a freshly-cut worktree has its dependencies in place.
  if (!options.skipInstall) {
    const pm = await detectPackageManager(worktree.wtPath);
    const installer = options.install ?? defaultInstall;
    await installer(pm, ["install"], worktree.wtPath);
  }

  // Reserve the block and pin every worker's port — the same reconciliation `pithy feature sync` runs, so
  // creating and later adding a worker go through one implementation.
  const { dev } = await syncFeatureDevConfig({
    mainRoot: worktree.root,
    worktreePath: worktree.wtPath,
    branch: worktree.branch,
    ...(options.registryPath !== undefined ? { registryPath: options.registryPath } : {}),
    ...(options.blockSize !== undefined ? { blockSize: options.blockSize } : {}),
    ...(options.discoverWorkers !== undefined ? { discoverWorkers: options.discoverWorkers } : {}),
  });

  // Migrate and seed run against the **worktree**, and discover its Workers themselves: the branch being
  // created is what decides which Workers exist and what each composes, and it may already differ from the
  // main checkout this command was run in.
  const migrate = options.migrate ?? localMigrate;
  const seed = options.seed ?? localSeed;
  // Both throw on failure, so reaching the return is what says they ran. Nothing in the report repeats it.
  await migrate({ projectDir: worktree.wtPath });
  await seed({ projectDir: worktree.wtPath });

  return {
    command: "feature.create",
    branch: worktree.branch,
    worktree: worktree.wtPath,
    worktreeCreated: worktree.created,
    base: worktree.base,
    dev,
  };
}

/** The default install runner — spawn the detected package manager. Lazy import keeps it out of the seam type. */
const defaultInstall: InstallRunner = async (command, args, cwd) => {
  const { execFile } = await import("node:child_process");
  const { promisify } = await import("node:util");
  await promisify(execFile)(command, args, { cwd });
};
