// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import { rm } from "node:fs/promises";
import { join } from "node:path";
import type { D1Database } from "@cloudflare/workers-types";
import { ValidationError } from "@pithy-sh/core/src/error/pithyError";
import { featureMarker } from "@pithy-sh/core/src/naming/environment";
import type { FeatureIdentity } from "@pithy-sh/core/src/naming/feature";
import type { VersionedValue } from "@pithy-sh/secrets/src/crypto/versionedValue";
import { type DevSecretsFile, initialDevSecret } from "@pithy-sh/secrets/src/dev/devSecretsFile";
import { devSecretPayload, type StatedSecret } from "@pithy-sh/secrets/src/dev/seedDevSecrets";
import { MASTER_KEY_BINDING } from "@pithy-sh/secrets/src/env/masterKeyBinding";
import { mintSecretValue } from "@pithy-sh/secrets/src/mintValue";
import { initialMasterKeyConfig } from "@pithy-sh/secrets/src/provision/provisionSecrets";
import { isMintableSecret, type SecretRegistry } from "@pithy-sh/secrets/src/registry";
import { SystemSecretsStore } from "@pithy-sh/secrets/src/store/systemSecretsStore";
import { managerMintedSecrets } from "../capabilities/mintSecrets";
import { readDevSecrets, readDevSecretsSource, writeDevSecrets } from "../devSecrets/file";
import { ensureDevSecretsDir } from "../devSecrets/location";
import { projectConfigDir, type StatePathOptions } from "../notifier/state";
import { writeFileAtomic } from "../project/atomic";

/**
 * **A feature's own secrets: generated once, at `pithy provision --feature`, and kept (#643).**
 *
 * A deployed Worker reads a `d1` secret from an encrypted row in its own `SECRETS` database, sealed under the
 * master key its `SECRETS_ENCRYPTION_KEYS` binding resolves. A declared environment's rows are written by its
 * secrets manager Worker. A feature has no manager, deliberately (#241), so nothing wrote them, and every
 * sign-in on a feature deployment answered `secrets/not_found`.
 *
 * ## Where the values live, and why both places
 *
 * - **In the feature's own Cloudflare resources**, because that is what the Worker reads: the master key and
 *   every arbitrary `cf-secrets-store` secret as the feature's own Secrets Store entries, and every `d1`
 *   secret as a row sealed into the feature's own `SECRETS` database.
 * - **In one file on the machine that provisioned it** — `<config>/<project>/features/f<issue>-<slug>.secrets.jsonc`,
 *   mode 600 — because the Secrets Store is write-only from this side and a sealed row opens only under the
 *   master key. Without a kept copy, nothing could seal a row, a re-run could not tell an existing value from a
 *   missing one, and the seed could not sign a dev login with the value the Worker checks.
 *
 * The file is keyed by project **and** feature, so two branches never share a value, and it is never the dev
 * secrets file: dev is the only environment that reads that (#159). It is outside every checkout, like the dev
 * file, so no commit can reach it. `pithy feature destroy` removes it with the rest of the feature.
 *
 * ## Stable, and never rotated in silence
 *
 * A value is generated only for a name the file does not already hold, and a value the file holds is the one
 * every destination is given. A re-run changes nothing. When the file is gone — a fresh CI runner, a new
 * machine — the values are generated again and the run **says so** (`regenerated`), because every session and
 * link signed with the old ones stops verifying.
 */

/** The directory under a project's config directory the kept feature files sit in. */
export const FEATURE_SECRETS_DIR = "features";

/** A feature's issue and slug, as the branch spells them. Checked again here because they become a file name. */
const ISSUE = /^[0-9]{1,6}$/;
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** `<config>/<project>/features/f<issue>-<slug>.secrets.jsonc` — this feature's kept secrets, and no other's. */
export function featureSecretsPath(identity: FeatureIdentity, options: StatePathOptions = {}): string {
  if (!ISSUE.test(identity.issue) || !SLUG.test(identity.slug)) {
    throw new ValidationError({
      message: "A feature's secrets file is named for its issue and slug, and these are not one.",
      action: "Run this from a feature/<issue>-<slug> branch.",
      detail: `feature identity issue "${identity.issue}", slug "${identity.slug}" is not a file name`,
    });
  }
  return join(
    projectConfigDir(identity.project, options),
    FEATURE_SECRETS_DIR,
    `${featureMarker(identity.issue)}-${identity.slug}.secrets.jsonc`,
  );
}

/** What a new kept file starts from. Its own words, because it is not the dev secrets file. */
const HEADER = `// One feature environment's own secret values, generated by pithy provision --feature and kept here.
// The deployed feature holds the same values. pithy feature destroy removes this file.
{}
`;

/**
 * The names a feature keeps: its master key, every `d1` secret the registry says may be minted, and every
 * mintable `cf-secrets-store` secret scoped to the environment. A `global` store secret is the project's, bound
 * as it is, and never copied. A secret somebody else issues is never invented — it stays the operator's to supply.
 */
export function keptSecretNames(registry: SecretRegistry): string[] {
  const names = new Set<string>(managerMintedSecrets(registry));
  for (const [name, entry] of Object.entries(registry)) {
    if (entry.backend !== "cf-secrets-store" || entry.keyed || entry.scope !== "environment") continue;
    if (name === MASTER_KEY_BINDING || isMintableSecret(entry)) names.add(name);
  }
  return [...names].sort();
}

/** A feature's kept values, and which of them this run generated. */
export interface KeptFeatureSecrets {
  /** The file they are kept in. */
  path: string;
  /** Every kept value, as the file states it: an envelope, or the master key's own payload. */
  values: DevSecretsFile;
  /** The names this run generated, because the file did not hold them. Empty on every re-run. */
  generated: string[];
}

/**
 * Read the kept values, generate any the file lacks, and write those back **before** anything is sent
 * anywhere. The order is the point: a run interrupted after the write resumes with the same values, and one
 * interrupted before it has sent nothing that a later run could disagree with.
 */
export async function keepFeatureSecrets(options: {
  registry: SecretRegistry;
  identity: FeatureIdentity;
  paths?: StatePathOptions;
}): Promise<KeptFeatureSecrets> {
  const path = featureSecretsPath(options.identity, options.paths);
  const values: DevSecretsFile = { ...(await readDevSecrets(path)) };
  const added: DevSecretsFile = {};
  for (const name of keptSecretNames(options.registry)) {
    if (Object.hasOwn(values, name)) continue;
    const entry = options.registry[name];
    if (!entry) continue;
    if (name === MASTER_KEY_BINDING) {
      added[name] = initialDevSecret(entry, await initialMasterKeyConfig());
    } else if (entry.devValue !== undefined) {
      added[name] = initialDevSecret(entry, mintSecretValue(entry.devValue));
    }
  }
  const generated = Object.keys(added).sort();
  if (generated.length > 0) {
    if ((await readDevSecretsSource(path)) === null) {
      await ensureDevSecretsDir(path);
      await writeFileAtomic(path, HEADER, { mode: 0o600 });
    }
    await writeDevSecrets(path, added);
    Object.assign(values, added);
  }
  return { path, values, generated };
}

/** One kept value as its destination takes it — the one materialization every destination shares (#323). */
export function keptPayload(kept: KeptFeatureSecrets, registry: SecretRegistry, name: string): StatedSecret | null {
  const entry = registry[name];
  if (!entry || !Object.hasOwn(kept.values, name)) return null;
  return devSecretPayload(entry, name, kept.values[name], kept.path);
}

/** What sealing a feature's `d1` secrets did. */
export interface SealedFeatureSecrets {
  /** Every kept `d1` secret the feature's database now holds, written this run or already there. */
  sealed: string[];
  /** Of those, the ones this run wrote — new, or replacing a row that was different or would not open. */
  written: string[];
  /** Of those written, the ones that replaced a row already there. */
  replaced: string[];
}

/**
 * Seal every kept `d1` secret into the feature's `SECRETS` database, under the kept master key.
 *
 * Through `SystemSecretsStore` — the reader the Worker itself uses, so what it decrypts is what this sealed,
 * by construction rather than by agreement. A row already holding the kept value is left alone; one that
 * differs, or that will not open because the master key was regenerated, is replaced.
 */
export async function sealFeatureSecrets(options: {
  kept: KeptFeatureSecrets;
  registry: SecretRegistry;
  database: D1Database;
}): Promise<SealedFeatureSecrets> {
  const master = keptPayload(options.kept, options.registry, MASTER_KEY_BINDING);
  const names = managerMintedSecrets(options.registry).filter((name) => Object.hasOwn(options.kept.values, name));
  if (!master || names.length === 0) return { sealed: [], written: [], replaced: [] };

  const store = await SystemSecretsStore.fromEnv({ SECRETS: options.database, SECRETS_ENCRYPTION_KEYS: master.text });
  const written: string[] = [];
  const replaced: string[] = [];
  for (const name of names) {
    const entry = options.registry[name];
    const stated = keptPayload(options.kept, options.registry, name);
    if (!entry || !stated) continue;
    // A row that will not open is a row to replace, not a failure: it was sealed under a key nobody holds now.
    const existing = await store.getValue(name).catch(() => null);
    if (existing && sameEnvelope(existing, stated.stored)) continue;
    await store.put(name, stated.stored, entry.valueType);
    written.push(name);
    if (existing !== undefined) replaced.push(name);
  }
  return { sealed: names, written, replaced };
}

/** Whether a stored envelope already is the kept one. */
function sameEnvelope(stored: VersionedValue, next: VersionedValue): boolean {
  if (stored.currentVersion !== next.currentVersion) return false;
  const versions = Object.keys(next.versions);
  if (Object.keys(stored.versions).length !== versions.length) return false;
  return versions.every((version) => stored.versions[version] === next.versions[version]);
}

/**
 * The kept values the seed signs with, or `null` when this machine holds none for the feature. Read-only: the
 * seed never generates one, because a value the deployment does not hold is a dev login nobody can open.
 */
export async function readFeatureSecrets(
  identity: FeatureIdentity,
  options: StatePathOptions = {},
): Promise<{ path: string; values: DevSecretsFile } | null> {
  const path = featureSecretsPath(identity, options);
  if ((await readDevSecretsSource(path)) === null) return null;
  return { path, values: await readDevSecrets(path) };
}

/** Remove a feature's kept values. Nothing there is not an error: teardown is idempotent. */
export async function forgetFeatureSecrets(identity: FeatureIdentity, options: StatePathOptions = {}): Promise<void> {
  await rm(featureSecretsPath(identity, options), { force: true });
}
