// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import type { Capability } from "@pithy-sh/core/src/capability/capability";
import { kitSource } from "../project/kitSource";
import { capabilityLoadError } from "./loadFailure";

/**
 * **A host Worker's composition, written as the entry it is deployed from** (#645).
 *
 * An app Worker composes capabilities, and a capability reaches an optional peer through its `compose` hook:
 * `payments()` finds the ledger, `testers()` finds auth. A host Worker composes nothing — it is a prebuilt
 * module inside the package, deployed straight from `node_modules` — so it has no hook and nothing to find a
 * peer in. It used to import the peer instead, behind a `try`, and wrangler's esbuild resolves a literal
 * specifier whether or not the branch holding it ever runs: every project that composed payments without the
 * ledger could not deploy its payments host at all.
 *
 * The CLI is the one party that sees both halves — the project's composition, and the host it is deploying — so
 * it writes the composition down. When a project composes a peer a host can use, the host is deployed from a
 * generated entry that imports the peer's surface from the project's own install, hands it to the host's
 * `providePeers`, and re-exports the host unchanged. A project that composes no such peer gets no entry and
 * the host deploys from its own `worker.ts`, exactly as before, with no specifier to resolve.
 *
 * **Absolute paths, resolved from the project.** The entry is written beside a config wrangler reads, which is
 * inside the installed package for a deploy and under `.wrangler/` for `pithy dev`; an absolute path resolves
 * the same from either, and resolving it from the project — never from the CLI — is #533's rule.
 */

/** One optional peer a host can be handed: the capability that supplies it and the module its surface is in. */
export interface HostPeer {
  /** The supplying capability's name — the key `providePeers` receives it under. */
  readonly capability: string;
  /** The module that exports the surface, as a project resolves it: `@pithy-sh/ledger/src/peer`. */
  readonly module: string;
  /** The surface's export name in that module: `ledgerPeer`. */
  readonly export: string;
}

/** How a host receives peers: the module exporting its `providePeers`, and which peers this composition has. */
export interface HostPeerSeam {
  /** The host's own module that exports `providePeers`: `@pithy-sh/payments/src/workflows/hostPeers`. */
  readonly provide: string;
  /** The peers this composition hands the host. Empty means the host deploys from its own entry. */
  needed(capability: Capability, siblings: readonly Capability[]): readonly HostPeer[];
}

/** The generated entry's file name for one environment, beside the config that names it. */
export function hostEntryFile(env: string): string {
  return `.pithy-host.${env}.ts`;
}

/** Resolve a kit module to its source on disk, or the actionable refusal a missing package earns. */
function source(projectDir: string, specifier: string): string {
  try {
    return kitSource(projectDir, specifier);
  } catch (error) {
    const pkg = specifier.split("/").slice(0, 2).join("/");
    throw capabilityLoadError(pkg.replace("@pithy-sh/", ""), pkg, error, projectDir);
  }
}

/**
 * The entry a host is deployed from when this composition hands it peers, or `undefined` when it hands none —
 * in which case the host deploys from its own `worker.ts` and nothing here is written.
 */
export function hostEntrySource(
  projectDir: string,
  host: { readonly entry: string; readonly peers?: HostPeerSeam },
  capability: Capability,
  siblings: readonly Capability[],
): string | undefined {
  const peers = host.peers?.needed(capability, siblings) ?? [];
  if (!host.peers || peers.length === 0) return undefined;
  const worker = JSON.stringify(source(projectDir, host.entry));
  const imports = peers.map(
    (peer, index) =>
      `import { ${peer.export} as peer${index} } from ${JSON.stringify(source(projectDir, peer.module))};`,
  );
  const handed = peers.map((peer, index) => `${JSON.stringify(peer.capability)}: peer${index}`).join(", ");
  return [
    "// Generated by pithy on every deploy, and removed after it. Not for editing.",
    "//",
    "// This host composes nothing, so the optional peers the project composes are handed to it here, from the",
    "// project's own install, before the host is re-exported unchanged.",
    ...imports,
    `import { providePeers } from ${JSON.stringify(source(projectDir, host.peers.provide))};`,
    "",
    `providePeers({ ${handed} });`,
    "",
    `export * from ${worker};`,
    `export { default } from ${worker};`,
    "",
  ].join("\n");
}
