// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import { join, relative, resolve, sep } from "node:path";
import { describe, expect, test } from "vitest";
import { readSource, sourcePaths } from "./sourceFiles";

/**
 * **The words this project writes are American.**
 *
 * Not a style preference — a census, over every file this repository writes prose into. `pithy-sh/dashboard#82`
 * standardized one word and stopped there, and #434 counted what the stopping left: hundreds of en-GB spellings
 * across doc comments, `.describe()` text, guides and manifests, in a kit that is otherwise American. A tree that
 * is mostly one way makes the other way harder to see, not easier, which is why this is a gate rather than a
 * sweep somebody repeats by hand every quarter.
 *
 * ## The rule, and the three things it is not about
 *
 * The rule is about **prose** — the sentences we write. Three kinds of en-GB spelling in this tree are not our
 * prose at all, and a census that flagged them would be asking for a rename of somebody else's data:
 *
 * 1. **A wire value.** `packages/email/src/data/enums.ts` stores an email job's state as `cancelled` and
 *    `packages/cloudflare/src/workers/workersBuildEvent.ts` reads the same spelling back from Cloudflare's
 *    build events. Those strings are in D1 rows and on the wire. Rewriting one is a migration and a breaking
 *    change, not a word swap — #434 says so at length — and it is a decision taken with a changeset, never by
 *    a gate.
 * 2. **A generated vendor notice.** A file a generator wrote carries the generator's wording, or somebody
 *    else's. It is fixed by fixing the generator, and editing it by hand is undone on the next run.
 * 3. **A quoted third-party string.** An error message or a field name from an API we do not own is quoted, not
 *    written. Correcting the quotation makes it stop matching what the API sends.
 *
 * ## How each exemption is decided, and why none of them is a list of paths
 *
 * **A hand-maintained allow-list of files is the defect `./turboInputs.test.ts` refuses one level up**, and #432
 * spent three days on why: a list is right on the day it is written and silently wrong afterwards, and the way
 * it goes wrong is that the gate keeps passing. So all three exemptions here are derived from the site.
 *
 * - **A lone token in code formatting is data.** A quoted or backticked run with no whitespace in it —
 *   `"cancelled"`, `` `subscription_cancelled` ``, `'colour'` — is a value, a key, an enum arm or an identifier
 *   being named. A sentence in quotes is prose and is still read, whitespace and all, which is why the
 *   `.describe()` beside an enum arm is reported while the arm is not. That single structural fact — **token,
 *   not sentence** — separates the email job's stored state from the sentence describing it, in the same file,
 *   with neither of them named anywhere. It is how this repository already writes about a wire value in prose,
 *   so nothing had to be restyled to earn it, and it is why this file can state its own word list without
 *   failing itself: a word named as a word is a token.
 * - **A generated file is the generator's output.** This repository has one convention for saying so, on the
 *   fourth line of every `version.generated.ts` and of `email/src/templates/precompiled.generated.ts`:
 *   `GENERATED by <script> — do not edit by hand.` The census reads that marker in a file's head and skips the
 *   file. The generator itself is source like any other; where it lives inside {@link ROOTS} the census reads it.
 * - **A quotation is marked where it is made.** One marker, `en-GB verbatim:`, in a comment on the offending
 *   line or the line above it, with the reason after the colon. It exempts **that line and no other** — never a
 *   file, never a directory — so it cannot grow into the list it replaces, and `git grep "en-GB verbatim:"` is the
 *   whole set of them. A marker with nothing after the colon exempts nothing: a shrug is not a reason.
 *
 * What this cannot do is check that a marker's reason is *true*, which is the same wall
 * `packages/ui-react/src/seededGates.test.ts` records for its own ledger. What it can do is make the claim
 * explicit, local, and greppable at the moment somebody makes it.
 *
 * ## Watched failing before it was trusted
 *
 * Run against the tree it was written for, with #434's sweep still ahead of it:
 *
 *     AssertionError: 938 en-GB spellings in 457 of 2025 files.
 *     - packages/audit/src/http/guards.ts:73:71  `customised` → customized
 *     - packages/audit/src/http/routeContract.test.ts:165:45  `greys` → grays
 *     - packages/auth/src/admin/users.ts:223:4  `optimisation` → optimization
 *     … and 935 more
 *
 * The very first run, over the untouched tree, found 973 in 464 files — and eight of them were in this
 * file's own header. It reads itself, like every file under {@link ROOTS}, which is the only way a census
 * can be believed about anybody else. Sixty-three of the findings were identifiers rather than sentences,
 * and the gate named them rather than deciding for the package that owns them. That package decided:
 * `offense()` in `./fileModes.ts`, and `analyze()` alongside `analyzeDrivers()` in `./workflowDrivers.ts`
 * and both of its importers. An identifier is either prose-shaped or it is a value something else
 * depends on, and only the package holding it knows which.
 *
 * Each finding names a file, a line, a column and the word, because a gate whose failure a reader cannot act on
 * is half a gate. The three exemptions were proven the same way and in the same tree: a wire value, a generated
 * notice and a quoted third-party message were each planted, the census stayed green over all three, and each
 * was removed again.
 *
 * ## What is outside its reach, said out loud
 *
 * {@link ROOTS} is #434's scope: each package's `src/`, `docs/` and `README.md`, plus `templates`, `docs`
 * and `tooling`. `packages/*​/templates`,
 * `apps/`, `scripts/`, `.changeset/` and the repository's root guides are prose this project writes too, and
 * they are not read here — roughly two hundred further occurrences sit in them. That is a boundary, not a
 * judgment, and it is written down rather than left for the next reader to discover from a green run: widening
 * {@link ROOTS} is one edit, and it should follow the sweep that empties them.
 *
 * `.svg` artwork and `tooling/license-headers/licenses/*.txt` are excluded by {@link PROSE}. The license texts
 * are the clearest case in the tree of somebody else's words: quoted in full, byte-for-byte, with no comment
 * syntax to carry a marker. A verbatim document is not prose we write.
 */

/** `packages/cli/src/ci` → the repository. */
const REPO_ROOT = resolve(import.meta.dirname, "..", "..", "..", "..");

/**
 * Where this project writes prose. #434's scope, and the header says what it leaves out.
 *
 * `packages` is narrowed to each package's `src/` below rather than here, because the walk is by directory and
 * the narrowing is by path.
 */
const ROOTS = ["packages", "templates", "docs", "tooling"] as const;

/**
 * File kinds that hold prose, by extension.
 *
 * Generous on purpose — a `.css` or an `.html` landing under {@link ROOTS} tomorrow is read without an edit
 * here. Two kinds are refused and both are documents rather than writing: `.svg`, which is artwork, and `.txt`,
 * which in this tree is a license quoted in full.
 */
const PROSE = [
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".md",
  ".mdx",
  ".json",
  ".jsonc",
  ".css",
  ".html",
  ".grit",
  ".sql",
  ".yml",
  ".yaml",
];

/** One en-GB spelling, and the American word that replaces it. */
interface BritishWord {
  /** The en-GB spelling, matched as a whole word. */
  readonly gb: string;
  /** What to write instead. */
  readonly us: string;
  /**
   * An American word that begins the same way and must survive. **This is why the census matches whole words
   * and never prefixes**: `cancellation` is American, and fifteen of them are correct where they stand. Every
   * one named here is asserted un-flagged below.
   */
  readonly near?: string;
  /** For a word that needs reading rather than replacing. Carried to the reader in the failure. */
  readonly read?: string;
}

/**
 * The stems that take `-ise` in en-GB and `-ize` in American English, with the suffixes enumerated.
 *
 * A stem list with named endings, never a prefix match: `recogn` yields exactly `recognise`, `recognised`,
 * `recognises`, `recognising`, `recognisable`, `recognisation`, `recogniser` and their plurals, and nothing
 * else. **The stems that are missing are the point.** `advertise`, `exercise`, `surprise`, `compromise`,
 * `franchise`, `merchandise`, `supervise`, `improvise` and `enterprise` are spelled with an `s` in American
 * English too, so `advert`, `exerc`, `surpr`, `compr`, `franch`, `merchand`, `superv`, `improv` and `enterpr`
 * are not here and must not be added.
 */
const ISE_STEMS = [
  "amort",
  "apolog",
  "author",
  "capital",
  "categor",
  "central",
  "character",
  "commercial",
  "custom",
  "digit",
  "emphas",
  "final",
  "general",
  "global",
  "initial",
  "item",
  "legitim",
  "local",
  "maxim",
  "memor",
  "minim",
  "monet",
  "normal",
  "optim",
  "organ",
  "parameter",
  "penal",
  "personal",
  "priorit",
  "random",
  "real",
  "recogn",
  "sanit",
  "serial",
  "special",
  "stabil",
  "standard",
  "summar",
  "synchron",
  "token",
  "util",
  "visual",
];

/** Every ending this repository could write on an `-ise` stem. The `s` becomes a `z` and nothing else moves. */
const ISE_ENDINGS = ["ise", "ised", "ises", "ising", "isable", "isation", "isations", "isational", "iser", "isers"];

/**
 * Everything that is not the `-ise` family, written out.
 *
 * Grouped by the rule it follows, because a reader adding a word wants the group rather than an alphabet. The
 * traps carry a {@link BritishWord.near}, and every one of them is a word already correct in this tree.
 */
const IRREGULAR: readonly BritishWord[] = [
  // `-our` → `-or`.
  { gb: "behaviour", us: "behavior" },
  { gb: "behaviours", us: "behaviors" },
  { gb: "behavioural", us: "behavioral" },
  { gb: "behaviourally", us: "behaviorally" },
  { gb: "colour", us: "color" },
  { gb: "colours", us: "colors" },
  { gb: "coloured", us: "colored" },
  { gb: "colouring", us: "coloring" },
  { gb: "colourful", us: "colorful" },
  { gb: "colourless", us: "colorless" },
  { gb: "favour", us: "favor" },
  { gb: "favours", us: "favors" },
  { gb: "favoured", us: "favored" },
  { gb: "favouring", us: "favoring" },
  { gb: "favourable", us: "favorable" },
  { gb: "favourite", us: "favorite" },
  { gb: "favourites", us: "favorites" },
  { gb: "honour", us: "honor" },
  { gb: "honours", us: "honors" },
  { gb: "honoured", us: "honored" },
  { gb: "honouring", us: "honoring" },
  { gb: "honourable", us: "honorable" },
  { gb: "neighbour", us: "neighbor" },
  { gb: "neighbours", us: "neighbors" },
  { gb: "neighbouring", us: "neighboring" },
  { gb: "neighbourhood", us: "neighborhood" },

  // `-ce` noun → `-se`. The verb is `license` on both sides of the Atlantic, so only the noun moves.
  { gb: "licence", us: "license", near: "licensed" },
  { gb: "licences", us: "licenses", near: "licensing" },
  { gb: "defence", us: "defense" },
  { gb: "defences", us: "defenses" },
  { gb: "offence", us: "offense" },
  { gb: "offences", us: "offenses" },
  { gb: "pretence", us: "pretense" },
  { gb: "practise", us: "practice" },
  { gb: "practised", us: "practiced" },
  { gb: "practising", us: "practicing" },

  // `-re` → `-er`.
  { gb: "centre", us: "center" },
  { gb: "centres", us: "centers" },
  { gb: "centred", us: "centered" },
  { gb: "centring", us: "centering" },
  { gb: "theatre", us: "theater" },
  { gb: "theatres", us: "theaters" },
  { gb: "metre", us: "meter" },
  { gb: "metres", us: "meters" },
  { gb: "litre", us: "liter" },
  { gb: "litres", us: "liters" },
  { gb: "fibre", us: "fiber" },
  { gb: "fibres", us: "fibers" },

  // `-yse` → `-yze`. `analyses` is missing on purpose: it is the American plural of `analysis` as well as the
  // en-GB verb, so matching it would refuse a word that is already right.
  { gb: "analyse", us: "analyze", near: "analyses" },
  { gb: "analysed", us: "analyzed" },
  { gb: "analysing", us: "analyzing" },
  { gb: "analyser", us: "analyzer" },
  { gb: "paralyse", us: "paralyze" },
  { gb: "paralysed", us: "paralyzed" },
  { gb: "catalyse", us: "catalyze" },

  // A doubled `l` before a suffix. American English doubles only under stress, so the traps live here.
  { gb: "cancelled", us: "canceled", near: "cancellation" },
  { gb: "cancelling", us: "canceling", near: "cancellations" },
  { gb: "labelled", us: "labeled" },
  { gb: "labelling", us: "labeling" },
  { gb: "modelled", us: "modeled" },
  { gb: "modelling", us: "modeling" },
  { gb: "signalled", us: "signaled" },
  { gb: "signalling", us: "signaling" },
  { gb: "travelled", us: "traveled" },
  { gb: "travelling", us: "traveling" },
  { gb: "traveller", us: "traveler" },
  { gb: "travellers", us: "travelers" },
  { gb: "marvellous", us: "marvelous" },

  // A single `l` where American English writes two. The opposite trap, and it bites harder: `fulfilled`,
  // `fulfilling`, `fulfillment`, `enrolled` and `enrolling` are already American and there are seventy-seven of
  // them. Only the exact words below move.
  { gb: "fulfil", us: "fulfill", near: "fulfilled" },
  { gb: "fulfils", us: "fulfills", near: "fulfillment" },
  { gb: "fulfilment", us: "fulfillment" },
  { gb: "enrol", us: "enroll", near: "enrolled" },
  { gb: "enrols", us: "enrolls", near: "enrolling" },
  { gb: "enrolment", us: "enrollment" },
  { gb: "instalment", us: "installment", near: "installed" },
  { gb: "instalments", us: "installments" },
  { gb: "skilful", us: "skillful" },
  { gb: "wilful", us: "willful" },

  // The rest, each its own rule.
  { gb: "judgement", us: "judgment" },
  { gb: "judgements", us: "judgments" },
  { gb: "grey", us: "gray" },
  { gb: "greys", us: "grays" },
  { gb: "greyscale", us: "grayscale" },
  { gb: "artefact", us: "artifact" },
  { gb: "artefacts", us: "artifacts" },
  { gb: "analogue", us: "analog" },
  { gb: "catalogue", us: "catalog", near: "catalogs" },
  { gb: "catalogues", us: "catalogs" },
  { gb: "catalogued", us: "cataloged" },
  { gb: "cataloguing", us: "cataloging" },
  {
    gb: "programme",
    us: "program",
    read: "right in both Englishes for a broadcast or a scheme, and `program` for anything a store or a computer runs",
  },
  {
    gb: "programmes",
    us: "programs",
    read: "right in both Englishes for a broadcast or a scheme, and `programs` for anything a store or a computer runs",
  },
];

/** Every word the census refuses: the irregulars, plus each `-ise` stem crossed with each ending. */
const WORDS: readonly BritishWord[] = [
  ...IRREGULAR,
  ...ISE_STEMS.flatMap((stem) =>
    ISE_ENDINGS.map((ending) => ({ gb: `${stem}${ending}`, us: `${stem}${ending.replace("is", "iz")}` })),
  ),
];

/** The word, whatever its case, with a boundary at each end. Whole words only — see {@link BritishWord.near}. */
const PATTERN = new RegExp(`\\b(${WORDS.map((word) => word.gb).join("|")})\\b`, "gi");

/** en-GB spelling → the entry that refuses it. */
const BY_WORD = new Map(WORDS.map((word) => [word.gb, word]));

/** The marker that says a line quotes somebody else. It exempts that line and the one after it, and no more. */
const QUOTED = /en-GB verbatim:\s*\S/;

/** What every generator in this repository writes into the head of what it produces. */
const GENERATED = /\bGENERATED by\b/;

/** How far into a file the generator's marker has to be, so a file mentioning it in prose is still read. */
const HEAD_LINES = 25;

/** One en-GB spelling, where it is. */
interface Finding {
  /** The file, relative to the repository root, in POSIX separators. */
  readonly path: string;
  /** 1-indexed line. */
  readonly line: number;
  /** 1-indexed column. */
  readonly column: number;
  /** The word as it is written, case and all. */
  readonly word: string;
  /** What to write instead, in the same case. */
  readonly american: string;
  /** Why this one wants reading rather than replacing, when it does. */
  readonly read?: string;
}

/** `american`, capitalized when `written` was. */
function matchCase(written: string, american: string): string {
  return written[0] === written[0]?.toUpperCase() ? `${american[0]?.toUpperCase()}${american.slice(1)}` : american;
}

/**
 * Every span on one line whose quoted content holds no whitespace — a token, not a sentence.
 *
 * Left to right, in whichever of the three quote characters opened it, and **a span that turns out to hold a
 * sentence is not skipped over**: that is what lets a backticked token inside a prose string literal still count,
 * which is how this repository names a wire value in a `.describe()`.
 */
function valueSpans(line: string): [number, number][] {
  const spans: [number, number][] = [];
  for (let index = 0; index < line.length; index += 1) {
    const quote = line[index];
    if (quote !== '"' && quote !== "'" && quote !== "`") continue;
    const close = line.indexOf(quote, index + 1);
    if (close === -1) continue;
    const inner = line.slice(index + 1, close);
    if (inner.length === 0 || /\s/.test(inner)) continue;
    spans.push([index + 1, close]);
    index = close;
  }
  return spans;
}

/** Every en-GB spelling in `text` that is this project's own prose. */
function census(path: string, text: string): Finding[] {
  const lines = text.split("\n");
  if (lines.slice(0, HEAD_LINES).some((line) => GENERATED.test(line))) return [];
  const found: Finding[] = [];
  for (const [index, line] of lines.entries()) {
    if (QUOTED.test(line) || (index > 0 && QUOTED.test(lines[index - 1] as string))) continue;
    const spans = valueSpans(line);
    for (const match of line.matchAll(PATTERN)) {
      const at = match.index;
      if (spans.some(([open, close]) => at >= open && at + match[0].length <= close)) continue;
      const word = BY_WORD.get(match[0].toLowerCase()) as BritishWord;
      found.push({
        path,
        line: index + 1,
        column: at + 1,
        word: match[0],
        american: matchCase(match[0], word.us),
        ...(word.read === undefined ? {} : { read: word.read }),
      });
    }
  }
  return found;
}

/** A path relative to the repository root, in POSIX form. */
function fromRoot(path: string): string {
  return relative(REPO_ROOT, path).split(sep).join("/");
}

/** Does this file hold prose? */
function isProse(name: string): boolean {
  return PROSE.some((extension) => name.endsWith(extension));
}

/**
 * Is this a package's own prose — `src/`, `docs/`, or the `README.md` at its root?
 *
 * All three ship. Sixteen of the eighteen manifests declare no `files`, so a package's `README.md` and its
 * `docs/` land in the tarball an adopter installs, and `@pithy-sh/payments` names `docs` explicitly. A README
 * is the most-read prose this project writes; leaving it out would have made the census truest about the
 * files fewest adopters open.
 *
 * Narrowed by the segment rather than by "holds `/src/` somewhere", which was the first spelling and was
 * wrong in a way that only showed up in a finding: `packages/ui-react/templates/src/routes/pithy/sign-in.tsx`
 * is a seeded adopter file under a package's `templates/`, and it matched.
 */
function isPackageProse(path: string): boolean {
  const segments = relative(join(REPO_ROOT, "packages"), path).split(sep);
  if (segments[1] === "src" || segments[1] === "docs") return true;
  return segments.length === 2 && segments[1] === "README.md";
}

/**
 * Every file the census reads. `packages` is narrowed to each package's own prose.
 *
 * Narrowed by the segment rather than by "holds `/src/` somewhere", which was the first spelling and was
 * wrong in a way that only showed up in a finding: `packages/ui-react/templates/src/routes/pithy/sign-in.tsx`
 * is a seeded adopter file under a package's `templates/`, and it matched. Whichever way that scope goes it
 * has to be the one the header claims.
 */
function corpus(): string[] {
  const found: string[] = [];
  for (const root of ROOTS) {
    for (const path of sourcePaths(join(REPO_ROOT, root), { keep: isProse })) {
      if (root === "packages" && !isPackageProse(path)) continue;
      found.push(path);
    }
  }
  return found;
}

/** One finding, as the reader sees it. */
function describeFinding(finding: Finding): string {
  const read = finding.read === undefined ? "" : `  — read it: ${finding.read}`;
  return `${finding.path}:${finding.line}:${finding.column}  ${finding.word} → ${finding.american}${read}`;
}

/** How many findings the failure lists before it stops. The headline always carries the true total. */
const LISTED = 50;

describe("the words this project writes are American", () => {
  test("no en-GB spelling in this repository's own prose", () => {
    const files = corpus();
    const findings = files.flatMap((path) => {
      const text = readSource(path);
      return text === null ? [] : census(fromRoot(path), text);
    });
    const report = findings.map(describeFinding);
    const headline = [
      `${findings.length} en-GB spellings in ${new Set(findings.map((finding) => finding.path)).size} of ${files.length} files.`,
      "Each line is file:line:column and the word to write instead.",
      "A wire value, an enum arm or a field name is exempt by being a lone token in quotes or backticks.",
      'A quotation from an API we do not own is exempt by "en-GB verbatim: <reason>" on its line or the line above.',
      report.length > LISTED ? `Listing the first ${LISTED} of ${report.length}.` : "",
    ]
      .filter(Boolean)
      .join("\n");
    expect(report.slice(0, LISTED), headline).toEqual([]);
  });

  test("the census reads the tree it says it reads", () => {
    // Shape 8 in `./sweepPopulation.test.ts`: a guard far below the real population passes over nothing. Every
    // root contributes, and the whole is near the 2,000 files measured on 2026-08-22 — a walk that broke and
    // returned three files would otherwise report a clean tree.
    const files = corpus().map(fromRoot);
    expect(files.length).toBeGreaterThanOrEqual(1900);
    for (const root of ROOTS) {
      expect(
        files.filter((path) => path.startsWith(`${root}/`)).length,
        `${root} contributes nothing to the census`,
      ).toBeGreaterThan(0);
    }
    expect(
      files.some((path) => path.endsWith(".md")),
      "no guide is read",
    ).toBe(true);
    expect(
      files.some((path) => path.endsWith(".ts")),
      "no TypeScript is read",
    ).toBe(true);
    // Narrowed to each package's own prose — `src/`, `docs/` and the root `README.md` — which is the scope
    // the header claims rather than an accident of the walk. `packages/ui-react/templates/src/` is the one
    // that reads as source and is not, and a package's `templates/` is somebody else's file waiting to be
    // copied rather than something we wrote.
    const PACKAGE_PROSE = /^packages\/[^/]+\/(src|docs)\/|^packages\/[^/]+\/README\.md$/;
    expect(files.filter((path) => path.startsWith("packages/") && !PACKAGE_PROSE.test(path))).toEqual([]);
  });
});

describe("the census is calibrated before it is trusted", () => {
  const AMERICAN = "The behavior is recognized, and the color is gray.";

  test("prose is read, and each finding names the file, the line, the column and the word", () => {
    const word = BY_WORD.get("behaviour") as BritishWord;
    const text = `line one\n// The ${word.gb} above.\n`;
    expect(census("a/b.ts", text)).toEqual([{ path: "a/b.ts", line: 2, column: 8, word: word.gb, american: word.us }]);
  });

  test("American prose is left alone", () => {
    expect(census("a/b.ts", AMERICAN)).toEqual([]);
  });

  test("a capital is reported with the American word capitalized, so the fix is the finding", () => {
    const gb = (BY_WORD.get("behaviour") as BritishWord).gb;
    const capital = `${gb[0]?.toUpperCase()}${gb.slice(1)}`;
    expect(census("a/b.ts", `// ${capital} first.`)[0]?.american).toBe("Behavior");
  });

  test("whole words only — the American near-neighbors survive", () => {
    // The trap #434 names twice: `cancellation`, `fulfilled`, `fulfillment`, `enrolled` and `analyses` are
    // already right, and a prefix match would ask for all of them to be broken. Every `near` in the table is a
    // real word from this tree, and each is swept here rather than trusted.
    const near = WORDS.flatMap((word) => (word.near === undefined ? [] : [word.near]));
    expect(near.length).toBeGreaterThanOrEqual(10);
    for (const word of near) {
      expect(census("a/b.ts", `// A sentence with ${word} in it.`), `${word} is American and was flagged`).toEqual([]);
    }
  });

  test("a word inside another word is not a word", () => {
    const gb = (BY_WORD.get("colour") as BritishWord).gb;
    expect(census("a/b.ts", `// The ${gb}Picker helper and a discolouration.`)).toEqual([]);
  });

  test("every entry replaces itself with something else, spelled once", () => {
    const spellings = WORDS.map((word) => word.gb);
    expect(new Set(spellings).size, "the table spells a word twice").toBe(spellings.length);
    for (const word of WORDS) {
      expect(word.us, `${word.gb} maps to itself`).not.toBe(word.gb);
      expect(word.us, `${word.gb} maps to something that is not one lower-case word`).toMatch(/^[a-z]+$/);
    }
    // The table is the rule. A collapse to a handful of words would pass every sweep above.
    expect(WORDS.length).toBeGreaterThanOrEqual(400);
  });
});

describe("a wire value is data, and data is not prose", () => {
  // The probe #434 asks for, taken from the two real ones: `packages/email/src/data/enums.ts` stores an email
  // job's state and `packages/cloudflare/src/workers/workersBuildEvent.ts` reads Cloudflare's build status back.
  // Both spell it the en-GB way, both are in D1 rows and on the wire, and neither is a word we chose to write.
  const gb = (BY_WORD.get("cancelled") as BritishWord).gb;

  test("an enum arm is a lone token, and is left alone", () => {
    expect(census("a/enums.ts", `  .enum(["pending", "sent", "${gb}"])`)).toEqual([]);
  });

  test("so is a field name, a key and a comparison against one", () => {
    expect(census("a/run.ts", `if (job.status === "${gb}") return;`)).toEqual([]);
    expect(census("a/api.ts", `const events = { "subscription_${gb}": handle };`)).toEqual([]);
  });

  test("and a wire value named in a doc comment the way this repository names them", () => {
    expect(census("a/run.ts", `/** Set when the operator has \`${gb}\` the job. */`)).toEqual([]);
  });

  test("but the sentence beside it is still prose", () => {
    // The whole of the exemption, in one pair of lines: the same word, in the same file, in quotes both times.
    // One is a token and one is a sentence, and only one of them is ours.
    const finding = census(
      "a/objects.ts",
      `  ends_at: z.string().describe("When access ends for a ${gb} subscription."),`,
    );
    expect(finding.map((entry) => entry.word)).toEqual([gb]);
  });

  test("a token in Markdown is a token too", () => {
    expect(census("docs/email.md", `The job moves to \`${gb}\` and stops.`)).toEqual([]);
    expect(census("docs/email.md", `The job is ${gb} and stops.`)).toHaveLength(1);
  });
});

describe("a generated file carries its generator's words, not ours", () => {
  // The real ones: every `version.generated.ts` and `email/src/templates/precompiled.generated.ts`, each stamped
  // with this marker on its fourth line. None of them holds an en-GB spelling today, so the probe below is a
  // fixture rather than a file from the tree — a vendor notice of the shape `pithy-sh/dashboard`'s generated
  // icon components carry, which is what #434 names.
  const gb = (BY_WORD.get("licence") as BritishWord).gb;
  const marker = `// ${"GENERATED"} by scripts/vendorNotices.ts — do not edit by hand.`;
  const notice = `// Distributed under the vendor's own ${gb}, quoted as they wrote it.`;

  test("a file whose head says a generator wrote it is skipped", () => {
    expect(census("a/notices.generated.ts", `${marker}\n${notice}\n`)).toEqual([]);
  });

  test("the same file without the marker is read, so the marker is doing the work", () => {
    expect(census("a/notices.ts", `${marker.replace("GENERATED", "Written")}\n${notice}\n`)).toHaveLength(1);
  });

  test("a marker further down than a head is not a head", () => {
    const padding = Array.from({ length: HEAD_LINES }, () => "//").join("\n");
    expect(census("a/notices.ts", `${padding}\n${marker}\n${notice}\n`)).toHaveLength(1);
  });
});

describe("a quotation is marked where it is made", () => {
  // The third exemption, and the only one that needs a person: a third-party error message is a sentence, so no
  // structural rule reaches it. No such string is in the tree today — every third-party en-GB spelling found in
  // #434 is a token, and tokens are already exempt — so this probe is a fixture, shaped like the message a rail
  // returns verbatim.
  const gb = (BY_WORD.get("cancelled") as BritishWord).gb;
  const quoted = `const KNOWN = "This subscription was already ${gb} by the customer.";`;

  test("the marker on the line above exempts the line", () => {
    const reason = "Lemon Squeezy returns this sentence; correcting it stops it matching.";
    expect(census("a/rail.ts", `// en-GB verbatim: ${reason}\n${quoted}`)).toEqual([]);
  });

  test("the marker on the line itself exempts it too", () => {
    expect(census("a/rail.ts", `${quoted} // en-GB verbatim: their wording, their spelling.`)).toEqual([]);
  });

  test("without the marker the same line is a finding", () => {
    expect(census("a/rail.ts", quoted)).toHaveLength(1);
  });

  test("a marker with no reason after it exempts nothing — a shrug is not an argument", () => {
    expect(census("a/rail.ts", `// en-GB verbatim:\n${quoted}`)).toHaveLength(1);
  });

  test("it reaches one line, never the file", () => {
    // The containment that keeps it from becoming the allow-list it replaces. Line two is covered by the marker
    // on line one; line three is not.
    const text = `// en-GB verbatim: their wording.\n${quoted}\n${quoted}`;
    expect(census("a/rail.ts", text).map((finding) => finding.line)).toEqual([3]);
  });
});
