/**
 * Precompile every template (and the shared partials) to Handlebars **template specs** and write them
 * to `src/templates/precompiled.generated.ts`. The Workers runtime forbids dynamic code generation
 * (`new Function`/`eval`) entirely — including at startup — so `Handlebars.compile()` cannot run there.
 * Precompiling here turns each source into a spec whose functions are defined at module-parse time;
 * the engine then builds render delegates with `Handlebars.template(spec)`, which never evals.
 *
 * Run via `bun run precompile`. It is wired into `build` and `test`, so the generated file is always
 * fresh; it is committed so `typecheck` and consumers have it without a build step.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import Handlebars from "handlebars";
import { emailFoot, emailHead } from "../src/templates/partials";
import { templates } from "../src/templates/registry";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "src", "templates", "precompiled.generated.ts");

const partials: Record<string, string> = { emailHead, emailFoot };
const partialSpecs = Object.entries(partials).map(
  ([name, source]) => `  ${JSON.stringify(name)}: ${Handlebars.precompile(source)},`,
);

const templateSpecs: string[] = [];
for (const def of Object.values(templates)) {
  templateSpecs.push(
    `  ${JSON.stringify(`${def.id}:subject`)}: ${Handlebars.precompile(def.subject, { noEscape: true })},`,
  );
  templateSpecs.push(`  ${JSON.stringify(`${def.id}:html`)}: ${Handlebars.precompile(def.html)},`);
  templateSpecs.push(`  ${JSON.stringify(`${def.id}:text`)}: ${Handlebars.precompile(def.text, { noEscape: true })},`);
}

const file = `// @ts-nocheck
// GENERATED by scripts/precompile.ts — do not edit by hand. Regenerate with \`bun run precompile\`.
// Handlebars template specs, precompiled so the Workers runtime never has to evaluate code at run time.

export const precompiledPartials = {
${partialSpecs.join("\n")}
};

export const precompiledTemplates = {
${templateSpecs.join("\n")}
};
`;

writeFileSync(outPath, file);
console.log(`Precompiled ${Object.keys(templates).length} templates + ${Object.keys(partials).length} partials.`);
