/**
 * Precompile every template (and the shared partials) to Handlebars **template specs** and write them
 * to `src/templates/precompiled.generated.ts`. The Workers runtime forbids dynamic code generation
 * (`new Function`/`eval`) entirely — including at startup — so `Handlebars.compile()` cannot run there.
 * Precompiling here turns each source into a spec whose functions are defined at module-parse time;
 * the engine then builds render delegates with `Handlebars.template(spec)`, which never evals.
 *
 * Run via `bun run precompile`. It is wired into `build` and `test`, so the generated file is always
 * fresh; it is committed so `typecheck` and consumers have it without a build step.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import Handlebars from "handlebars";
import { emailFoot, emailHead } from "../src/templates/partials";
import { templates } from "../src/templates/registry";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "src", "templates", "precompiled.generated.ts");

// Read the license rather than hard-code it, for the same reason `scripts/license-headers.ts` does:
// the `license` field is the single source of truth. Hard-coding `MIT` here would survive right up
// until this package's license changed, at which point the gate would report `wrong-header`, `--fix`
// would correct it, and the next `bun run precompile` would put it back — and precompile runs inside
// both `build` and `test:node`, so the repo would oscillate and CI would flap.
const { license } = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8")) as { license: string };

/**
 * Data frames are compiled in, on every spec.
 *
 * The `t` / `tn` / `severityLabel` helpers read the render's translator off `@root`, which only exists
 * where the compiler emitted a data frame. Handlebars decides that per template by looking for a `@`
 * variable in the source, and none of these bodies has one — so without this flag the helpers would
 * find no root, silently fall back to English, and every translated email would render in the language
 * the kit is written in with nothing failing anywhere. Asked for explicitly rather than inferred, for
 * that reason: the failure mode is silent and it is the whole point of the feature.
 *
 * Never per locale. One spec per template id, one partial registry, and the words come from the
 * catalog at render — see `src/templates/messages.ts` for why duplicating 132KB of identical table
 * markup per language was the wrong trade.
 */
const DATA_FRAME = { data: true } as const;

const partials: Record<string, string> = { emailHead, emailFoot };
const partialSpecs = Object.entries(partials).map(
  ([name, source]) => `  ${JSON.stringify(name)}: ${Handlebars.precompile(source, DATA_FRAME)},`,
);

const templateSpecs: string[] = [];
for (const def of Object.values(templates)) {
  templateSpecs.push(
    `  ${JSON.stringify(`${def.id}:subject`)}: ${Handlebars.precompile(def.subject, { ...DATA_FRAME, noEscape: true })},`,
  );
  templateSpecs.push(`  ${JSON.stringify(`${def.id}:html`)}: ${Handlebars.precompile(def.html, DATA_FRAME)},`);
  templateSpecs.push(
    `  ${JSON.stringify(`${def.id}:text`)}: ${Handlebars.precompile(def.text, { ...DATA_FRAME, noEscape: true })},`,
  );
}

// The SPDX header is emitted here rather than stamped afterwards: this file is rewritten on every
// `bun run precompile`, so a header applied to the output would be gone by the next build. It is
// committed like any other source file, so it has to carry one.
const file = `// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: ${license}

// @ts-nocheck
// GENERATED by scripts/precompile.ts — do not edit by hand. Regenerate with \`bun run precompile\`.
// Handlebars template specs, precompiled so the Workers runtime never has to evaluate code at run time.

export const precompiledPartials = {
${partialSpecs.join("\n")}
};

export const precompiledTemplates = {
${templateSpecs.join("\n")}
};
`;

writeFileSync(outPath, file);
console.log(`Precompiled ${Object.keys(templates).length} templates + ${Object.keys(partials).length} partials.`);
