// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

// GENERATED by scripts/stampVersions.ts — do not edit by hand. Regenerate with `bun run stamp-versions`.
//
// A Worker cannot read its own package.json, so this is how @pithy-sh/media knows its own version at
// runtime. The capability attaches it, and `GET /control-plane/manifest` reports it per capability —
// which is what answers "should this project upgrade" and "is this customer exposed to what we just
// fixed". Those questions are only answerable per module, because a project composes some capabilities
// and not others.

/** This package's npm name — the join key against a release feed. */
export const PACKAGE_NAME = "@pithy-sh/media";

/** This package's version, stamped from its own package.json at generation time. */
export const PACKAGE_VERSION = "0.0.0";
