// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { normalizeAddress } from "@pithy-sh/core/src/address/address";
import {
  DEV_LOGIN_CLAIM_PARAM,
  DEV_LOGIN_PATH,
  DEV_LOGIN_ROUTE,
  type DevLogin,
  DevLogins,
} from "@pithy-sh/core/src/seed/devLogin";

/**
 * The `pithy dev` end of the dev login: say that there is one, and how to use it — **without ever
 * saying what it is**.
 *
 * The banner is still where this belongs, because it is the only place a developer reliably looks and a
 * seeded session nobody discovers has removed no friction. What changed is what the banner is allowed to
 * carry. It used to hand over the credential itself:
 *
 * ```
 * document.cookie = "better-auth.session_token=…; path=/; max-age=31535918"
 * ```
 *
 * A working session cookie, rendered as text, on every `pithy dev`. Terminals scroll back, output gets
 * tee'd and piped, screenshots get pasted into issues — a value printed once is a value at rest in
 * places nobody chose. `core/src/seed/seed.ts` already treats the login artifact as sensitive for
 * exactly this reason, so printing it was the one place the rule was suspended by design.
 *
 * Now the session travels over HTTP, from the Worker to the browser, and the terminal carries a keypress.
 *
 * ## The claim, and the one place it is unavoidable — `#572`
 *
 * The URL carries a signed claim naming the user to sign in as, because the seed writes a file and a
 * Worker has no filesystem to read it from. **That claim is a credential**: presenting it to a `dev`
 * composition mints a session. So it is kept out of printed output wherever the CLI can open the browser
 * itself, which is every interactive run with one worker — the ordinary case, where nothing is printed
 * but a name.
 *
 * It cannot be kept out of the rest. A non-interactive run has no keypress, and a run with two workers
 * has no defensible guess about which one to open, so both must print a link a person can click — and a
 * link that omitted the claim would 404. {@link claimIsPrinted} names those cases in one place so the
 * test can assert the boundary rather than the wording.
 *
 * **A session cookie must still never appear in a string this module returns**, and neither must the
 * claim in any line outside that boundary. Both are asserted directly, over every line every function
 * here can produce, rather than trusted to review.
 */

/** A started worker the dev-login route can be opened on — one that composes auth. */
export interface DevLoginTarget {
  /** The worker's name, as `pithy dev` labels it. */
  name: string;
  /** Its localhost origin, from the pinned port. */
  origin: string;
}

/** What the banner needs to know about the session it is describing. */
export interface DevLoginBanner {
  /** Whether a keypress can be offered — a TTY that is not being piped, and not `--json`. */
  interactive: boolean;
  /** The started workers that carry the route. Empty is a real answer, and gets its own sentence. */
  targets: readonly DevLoginTarget[];
  /**
   * Whether this run is under CI, where the capability refuses to register the route at all.
   *
   * The keypress follows the route. Offering `l` here would be offering a 404, and it is the *only*
   * refusal `pithy dev` can see coming: every other one is about what is running.
   */
  ci: boolean;
}

/** The one sentence for a run under CI. Stated once, because the banner and the keypress both say it. */
const CI_REFUSAL = "the dev-login route is not registered under CI.";

/** What pressing `l` should do: open this URL, and say these lines. Either half may be empty. */
export interface DevLoginKeyAction {
  /** The URL to open, or `undefined` when there is nothing to open — never a URL that would 404. */
  url?: string;
  /** What to print. A refusal always says what to do about it; an open says what it is opening. */
  lines: string[];
}

/** The two refusals that are about the artifact rather than about this run. Said by the keypress and the selection alike. */
const NOT_SEEDED = "No dev login is seeded. Run pithy seed, then press l again.";
const ALL_EXPIRED = "The seeded dev login has expired. Run pithy seed to mint a fresh one.";

/**
 * How many identities a one-key numbered choice can carry: the digits `1`–`9`.
 *
 * Past it the list needs filtering rather than counting, which is the `@clack/prompts` select. The number
 * is the keyboard's, not a preference — there is no tenth digit to bind.
 */
export const MAX_KEY_CHOICES = 9;

/**
 * Read every seeded dev login, or `undefined` when there is none. Validated — an unreadable file is no login.
 *
 * **The single-entry file this replaced does not parse, and that is the whole migration — `#667`.** The
 * artifact is gitignored, transient and regenerated by `pithy seed`, so the honest degradation is the one
 * that was already here: no dev-login line until the next seed, rather than a crash.
 */
export async function readDevLogins(projectDir: string): Promise<DevLogins | undefined> {
  try {
    const parsed = DevLogins.safeParse(JSON.parse(await readFile(join(projectDir, DEV_LOGIN_PATH), "utf8")));
    return parsed.success ? parsed.data : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Where a worker serves the dev login, carrying the claim that says who to sign in as.
 *
 * The route and the parameter are both core's, so both ends spell them the same way once. **The claim
 * travels in the URL because the artifact is a file and a Worker has no filesystem — `#572`.** It used
 * to need nothing: the route found the one seeded session in D1. That session is what the product's own
 * sign-out revoked, which is the whole of the bug this replaced.
 */
export function devLoginUrl(origin: string, claim: string): string {
  return `${origin}${DEV_LOGIN_ROUTE}?${DEV_LOGIN_CLAIM_PARAM}=${claim}`;
}

/**
 * A usable login, or `undefined`.
 *
 * An expired cookie is worse than no cookie: it looks like a way in, fails silently in the browser, and
 * sends someone hunting for a bug in auth. The banner therefore treats expiry as absence; the keypress
 * does not, because someone who pressed `l` asked a question and deserves the reason.
 */
function usable(login: DevLogin | undefined, now: Date): DevLogin | undefined {
  if (!login) return undefined;
  return login.expiresAt.getTime() > now.getTime() ? login : undefined;
}

/**
 * Every identity that can still be signed in as, in the order the seed wrote them.
 *
 * **Expiry applies per entry — `#667`.** One stale claim used to be the only claim, so it took the
 * feature down with it; now it takes one name out of the picker and leaves the rest working. The record's
 * own insertion order is the only ordering there is, and it is the seed's, so a reseed does not reshuffle
 * somebody's list for no reason.
 */
export function usableDevLogins(logins: DevLogins | undefined, now: Date): DevLogin[] {
  return Object.values(logins ?? {}).filter((login) => usable(login, now) !== undefined);
}

/**
 * Whether a claim has to be printed, for one surface and one shape of run.
 *
 * **The two surfaces differ, and a single predicate hid that.** The banner prints a link only when there
 * is no keypress to offer instead — with a terminal it says *press l* and names no URL, however many
 * workers are running. The keypress prints links only when there is more than one worker, because with
 * one it opens the browser itself and with several there is no defensible guess.
 *
 * Stated here rather than at the call sites so the boundary is a thing a test can assert and a reader
 * can find. True means a person has to click a link themselves, and the claim rides in it; false means
 * the terminal sees a name and nothing else.
 */
export function claimIsPrinted(where: "banner" | "keypress", interactive: boolean, targets: number): boolean {
  return where === "banner" ? targets > 0 && !interactive : targets > 1;
}

/** One indented `name: url` line per target — the shape both the banner and the keypress list choices in. */
function choices(targets: readonly DevLoginTarget[], claim: string): string[] {
  return targets.map((target) => `  ${target.name}: ${devLoginUrl(target.origin, claim)}`);
}

/**
 * The same list across both axes: every identity against every worker, identity-major.
 *
 * Only reached where there is no keypress to offer, so the reader is clicking a link and the label has to
 * say which link — with one identity that is the worker's name alone, exactly as it always was, and with
 * several it is both. A row per pair rather than a nested block: a banner is scanned, not read.
 */
function identityChoices(targets: readonly DevLoginTarget[], logins: readonly DevLogin[]): string[] {
  const only = logins.length === 1 ? logins[0] : undefined;
  if (only) return choices(targets, only.claim);
  return logins.flatMap((login) =>
    targets.map((target) => `  ${login.email} at ${target.name}: ${devLoginUrl(target.origin, login.claim)}`),
  );
}

/**
 * Who the banner is about: the one seeded user, or how many there are.
 *
 * **With a choice to make there is no user to name.** Naming the first would be picking one, which is the
 * thing this module never does — and a count is what tells a reader that `l` is going to ask.
 */
function whoIs(logins: readonly DevLogin[]): string {
  const only = logins.length === 1 ? logins[0] : undefined;
  return only ? only.email : `${logins.length} identities`;
}

/**
 * The banner lines for the seeded dev logins — empty when there are none, and empty when all have expired.
 *
 * Four shapes, because the honest sentence differs: a keypress where there is a keypress and one target,
 * a URL where there is not, the choices where more than one worker composes auth, and a plain statement
 * where nothing running carries the route at all. Nothing here guesses.
 *
 * **The user axis rides in front of all four — `#667`.** Each shape names one user or a count, and the
 * interactive one says what `l` is about to ask for; none of them changes which shape a run gets, because
 * that is a question about workers and interactivity and how many users exist has no bearing on it. A
 * project with one usable identity gets the single-user sentence whatever the seed wrote, because that is
 * what it is.
 */
export function devLoginLines(logins: DevLogins | undefined, now: Date, banner: DevLoginBanner): string[] {
  const live = usableDevLogins(logins, now);
  if (live.length === 0) return [];
  const who = whoIs(live);
  if (banner.ci) return [`Dev login: ${who} — ${CI_REFUSAL}`];
  const targets = banner.targets;

  if (targets.length === 0) {
    return [`Dev login: ${who} — no running worker composes auth, so there is nothing to open.`];
  }
  if (banner.interactive) {
    return [`Dev login: ${who} — press l to ${pressVerb(live.length, targets.length)}.`];
  }
  const only = live.length === 1 ? live[0] : undefined;
  const first = targets[0];
  if (only && targets.length === 1 && first) {
    return [`Dev login: ${who} — open ${devLoginUrl(first.origin, only.claim)} to sign in.`];
  }
  return [`Dev login: ${who} — open one of these to sign in.`, ...identityChoices(targets, live)];
}

/** What `l` is about to ask for, named before it is pressed — one axis, both, or neither. */
function pressVerb(identities: number, targets: number): string {
  if (identities === 1)
    return targets === 1 ? "open a signed-in browser" : "choose a worker and open a signed-in browser";
  return targets === 1 ? "choose who to be and open a signed-in browser" : "choose who to be, then a worker";
}

/**
 * What `l` does, decided without touching the terminal or the network so it can be tested as a value.
 *
 * Every refusal names the command that fixes it and opens nothing. A browser sent to a route that 404s
 * is worse than a sentence: it looks like the feature is broken rather than like the session is missing.
 */
export function devLoginKeyAction(
  login: DevLogin | undefined,
  now: Date,
  targets: readonly DevLoginTarget[],
  ci = false,
): DevLoginKeyAction {
  if (!login) return { lines: [NOT_SEEDED] };
  if (!usable(login, now)) return { lines: [ALL_EXPIRED] };
  // Before the targets, because this refusal is about the route rather than about what is running: the
  // workers below all compose auth and none of them mounted it.
  if (ci) return { lines: [`Not opening — ${CI_REFUSAL}`] };
  if (targets.length === 0) return { lines: ["No running worker composes auth, so there is nothing to open."] };

  const first = targets[0];
  if (targets.length === 1 && first) {
    // **The URL is opened, not printed.** It carries the claim, and this is the path where the CLI can
    // hand it to a browser without it passing through a terminal somebody tees, pastes or screenshots.
    return { url: devLoginUrl(first.origin, login.claim), lines: [`Opening the dev login for ${login.email}.`] };
  }
  // More than one worker carries the route, and they are separate origins — a cookie set on one signs
  // nobody into the other. There is no defensible guess, so the choice is printed.
  return { lines: ["More than one worker composes auth. Open the one you want:", ...choices(targets, login.claim)] };
}

/**
 * One seeded identity, as `pithy dev --json` reports it — **everything but the claim**.
 *
 * The fields are listed rather than projected off a `DevLogin`, which is the point: a claim is a
 * credential, and a machine-readable line is as public as a printed one. Spreading the entry and deleting
 * a key would put the omission one edit away from being undone by a field nobody thought about.
 */
export interface DevIdentity {
  /** The seeded user's id — canonical, and what a record is keyed by. */
  userId: string;
  /** The seeded user's email — what a person recognizes. */
  email: string;
  /** When this identity's claim stops being accepted, ISO-8601. */
  expiresAt: string;
}

/** The identities a script can select against: the usable ones, with no claim on any of them. */
export function devLoginIdentities(logins: DevLogins | undefined, now: Date): DevIdentity[] {
  return usableDevLogins(logins, now).map((login) => ({
    userId: login.userId,
    email: login.email,
    expiresAt: login.expiresAt.toISOString(),
  }));
}

/**
 * Which shape of choice `l` has to offer, decided as a value — the user axis, and nothing else.
 *
 * **It composes in front of {@link devLoginKeyAction}, never into it.** That function keeps its signature
 * and all four of its shapes; this one decides only *which* `DevLogin` it is handed. Folding users into it
 * would turn a workers axis into a workers × users matrix and make the boundary harder to state, for no
 * gain.
 *
 * `only` carries the entry — or `undefined`, or an expired one — straight through, so the four refusals
 * downstream keep saying which of them it was. Nothing here guesses between identities.
 */
export type DevLoginChoice =
  | { kind: "only"; login: DevLogin | undefined }
  | { kind: "keys" | "select"; logins: readonly DevLogin[] };

/** {@link DevLoginChoice}, for a record and a moment. `keys` up to {@link MAX_KEY_CHOICES}, `select` past it. */
export function devLoginChoice(logins: DevLogins | undefined, now: Date): DevLoginChoice {
  const live = usableDevLogins(logins, now);
  // One live identity needs no choosing, and none at all still has a reason to give: the first entry of
  // an all-expired record is what makes the refusal say *expired* rather than *never seeded*.
  if (live.length <= 1) return { kind: "only", login: live[0] ?? Object.values(logins ?? {})[0] };
  return { kind: live.length <= MAX_KEY_CHOICES ? "keys" : "select", logins: live };
}

/** An identity resolved from a value, or the refusal that names what was asked for. Never both. */
export interface DevLoginSelection {
  /** The identity, when the value named one that is still usable. */
  login?: DevLogin;
  /** Why not, when it did not. Empty on success — the caller is opening something, not saying anything. */
  lines: string[];
}

/**
 * Resolve a value to one seeded identity: **a `userId` or an `email`**.
 *
 * Both, because one is canonical and the other is what a person actually knows. The email is matched
 * normalized on both sides, for the reason `dev.json` always was — refusing to sign in over the capital in
 * `Ada@example.com` would be a puzzle rather than an error.
 *
 * An unknown value is refused by name and resolves nothing: a browser sent somewhere on a guess is worse
 * than a sentence. An expired identity is unknown here for the same reason the picker omits it — it looks
 * like a way in and fails silently in the browser.
 */
export function selectDevLogin(logins: DevLogins | undefined, now: Date, value: string): DevLoginSelection {
  const live = usableDevLogins(logins, now);
  if (live.length === 0) {
    return { lines: [Object.keys(logins ?? {}).length === 0 ? NOT_SEEDED : ALL_EXPIRED] };
  }
  const wanted = value.trim();
  const address = normalizeAddress(wanted);
  const login = live.find((candidate) => candidate.userId === wanted || normalizeAddress(candidate.email) === address);
  if (login) return { login, lines: [] };
  // The value as it was typed, and then who there is — the actionable half of every refusal here.
  return { lines: [`No seeded identity is ${value}. Seeded: ${live.map((entry) => entry.email).join(", ")}.`] };
}

/** The identity a digit named, or `undefined`. Every other key stays unbound rather than guessing. */
export function pickDevLoginByKey(logins: readonly DevLogin[], key: string): DevLogin | undefined {
  if (!/^[1-9]$/.test(key)) return undefined;
  return logins[Number(key) - 1];
}

/** The numbered list `l` prints before waiting for a digit. Names only emails — a claim is not a label. */
export function devLoginChoiceLines(logins: readonly DevLogin[]): string[] {
  return [
    `Which identity? Press 1–${logins.length}.`,
    ...logins.map((login, index) => `  ${index + 1}  ${login.email}`),
  ];
}
