// SPDX-FileCopyrightText: 2026 Pithy
// SPDX-License-Identifier: MIT

import Handlebars from "handlebars";
import { mintToken } from "../crypto/token";
import { EmailInvalidPayloadError, EmailTemplateNotFoundError } from "../error/errors";
import { precompiledPartials, precompiledTemplates } from "./precompiled.generated";
import { type EmailTemplate, templates } from "./registry";
import { type EmailTheme, widthPx } from "./theme";

/**
 * The render engine. Templates are compiled **once at module load** — which in a Worker happens during
 * isolate startup, where dynamic compilation is permitted — and cached, so a send never compiles or
 * evals at request time (CLAUDE.md §Email: "precompiled, no runtime compile/eval"). Rendering is then
 * pure string substitution.
 *
 * Tracking is applied here, not in the template: callback tokens are minted ahead of render (signing
 * is async; Handlebars helpers are not) and the resulting URLs are placed into the render context.
 * Click tracking rewrites the declared link locations; open tracking injects a pixel; and a marketing
 * template always gets an unsubscribe link — it cannot render without one.
 */

/** The mount prefix of the callback routes. Tracking URLs are built against `${baseUrl}${CALLBACK_BASE}`. */
export const CALLBACK_BASE = "/_pithy/email";

// Build the engine from the **precompiled** specs (generated by `scripts/precompile.ts`).
// `Handlebars.template(spec)` wraps spec functions that were defined at module-parse time — it never
// calls `eval`/`new Function`, so this works in the Workers runtime, which forbids runtime code
// generation entirely (CLAUDE.md §Email: "precompiled, no runtime compile/eval").
const hbs = Handlebars.create();
for (const [name, spec] of Object.entries(precompiledPartials)) {
  hbs.registerPartial(name, hbs.template(spec));
}

interface Compiled {
  def: EmailTemplate;
  subject: HandlebarsTemplateDelegate;
  html: HandlebarsTemplateDelegate;
  text: HandlebarsTemplateDelegate;
}

function delegate(key: string): HandlebarsTemplateDelegate {
  const spec = (precompiledTemplates as Record<string, unknown>)[key];
  if (!spec) throw new Error(`missing precompiled template spec '${key}' — run \`bun run precompile\``);
  return hbs.template(spec);
}

const compiled = new Map<string, Compiled>(
  Object.values(templates).map((def) => [
    def.id,
    { def, subject: delegate(`${def.id}:subject`), html: delegate(`${def.id}:html`), text: delegate(`${def.id}:text`) },
  ]),
);

/** The signing + addressing context a tracked render needs. Shaped to plug straight into the send path. */
export interface RenderTracking {
  /** The public base URL of the app worker; callback links are built against it. */
  baseUrl: string;
  /** The job this render belongs to — embedded in every token. */
  jobId: string;
  /** The recipient address — embedded in every token. */
  recipient: string;
  /** The marketing campaign id, for click/open attribution. */
  campaignId?: string;
  /** The current signing key value (from `@pithy-sh/secrets`). */
  key: string;
  /** The current signing key version, recorded as the token `kid`. */
  kid: string;
  /** When the tokens (and so the links) expire. */
  expiresAt: Date;
  /** Whether to inject the open-tracking pixel. */
  openTracking: boolean;
  /** Whether to rewrite links to tracked click callbacks. */
  clickTracking: boolean;
}

/** A rendered email: the three parts a send needs. */
export interface RenderResult {
  subject: string;
  html: string;
  text: string;
}

/** Look up a template by id, or throw `email/template_not_found`. */
export function getTemplate(id: string): EmailTemplate {
  const found = compiled.get(id);
  if (!found) throw new EmailTemplateNotFoundError({ detail: `no template registered with id '${id}'` });
  return found.def;
}

/** The registered template ids, for introspection and the CLI. */
export function listTemplates(): EmailTemplate[] {
  return Object.values(templates);
}

/**
 * Validate a payload against its template and render just the subject line. Used at enqueue to fail
 * fast on a bad payload and to store the job's subject without rendering the whole body. Throws
 * `email/template_not_found` or `email/invalid_payload`.
 */
export function renderSubject(templateId: string, payload: unknown, theme: EmailTheme): string {
  const entry = compiled.get(templateId);
  if (!entry) throw new EmailTemplateNotFoundError({ detail: `no template registered with id '${templateId}'` });
  const parsed = entry.def.payload.safeParse(payload);
  if (!parsed.success) {
    const summary = parsed.error.issues.map((i) => `${i.path.join(".") || "<root>"}:${i.code}`).join(", ");
    throw new EmailInvalidPayloadError({ detail: `template '${templateId}' payload invalid: ${summary}` });
  }
  return entry
    .subject({ ...(parsed.data as Record<string, unknown>), theme, layoutWidth: widthPx(entry.def.width) })
    .trim();
}

function trimTrailingSlash(value: string): string {
  return value.endsWith("/") ? value.slice(0, -1) : value;
}

/** Rewrite one declared link path (`"url"` or `"articles[].link"`) in the context through `makeUrl`. */
async function rewriteLink(
  context: Record<string, unknown>,
  path: string,
  label: string,
  makeUrl: (destination: string, label: string) => Promise<string>,
): Promise<void> {
  const arrayMatch = path.split("[].");
  if (arrayMatch.length === 2) {
    const arrayKey = arrayMatch[0];
    const field = arrayMatch[1];
    if (!arrayKey || !field) return;
    const items = context[arrayKey];
    if (Array.isArray(items)) {
      for (let i = 0; i < items.length; i += 1) {
        const item = items[i] as Record<string, unknown>;
        if (item && typeof item[field] === "string")
          item[field] = await makeUrl(item[field] as string, `${label}-${i}`);
      }
    }
    return;
  }
  if (typeof context[path] === "string") context[path] = await makeUrl(context[path] as string, label);
}

/**
 * Render a template to `{ subject, html, text }`. Validates the payload against the template's schema
 * (throws `email/invalid_payload`), applies click/open tracking and the marketing unsubscribe link per
 * the `tracking` context, then substitutes. A marketing template with no tracking context throws —
 * it cannot render without an unsubscribe link.
 */
export async function renderEmail(
  templateId: string,
  payload: unknown,
  theme: EmailTheme,
  tracking?: RenderTracking,
): Promise<RenderResult> {
  const entry = compiled.get(templateId);
  if (!entry) throw new EmailTemplateNotFoundError({ detail: `no template registered with id '${templateId}'` });

  const parsed = entry.def.payload.safeParse(payload);
  if (!parsed.success) {
    const summary = parsed.error.issues.map((i) => `${i.path.join(".") || "<root>"}:${i.code}`).join(", ");
    throw new EmailInvalidPayloadError({ detail: `template '${templateId}' payload invalid: ${summary}` });
  }

  const isMarketing = entry.def.category === "marketing";
  if (isMarketing && !tracking) {
    throw new EmailInvalidPayloadError({
      message: "Marketing emails require an unsubscribe link.",
      detail: `template '${templateId}' is marketing but no signing/tracking context was provided`,
    });
  }

  const context: Record<string, unknown> = {
    ...(parsed.data as Record<string, unknown>),
    theme,
    layoutWidth: widthPx(entry.def.width),
  };

  if (tracking) {
    const base = trimTrailingSlash(tracking.baseUrl) + CALLBACK_BASE;
    const mint = (kind: "click" | "open" | "unsubscribe", extra: { destination?: string; linkLabel?: string }) =>
      mintToken(
        { kind, jobId: tracking.jobId, recipient: tracking.recipient, campaignId: tracking.campaignId, ...extra },
        { key: tracking.key, kid: tracking.kid, expiresAt: tracking.expiresAt },
      );

    if (tracking.clickTracking) {
      for (const link of entry.def.links) {
        await rewriteLink(context, link.path, link.label, async (destination, label) => {
          const token = await mint("click", { destination, linkLabel: label });
          return `${base}/c/${token}`;
        });
      }
    }

    if (tracking.openTracking) {
      context.openPixelUrl = `${base}/o/${await mint("open", {})}.png`;
    }

    // A marketing template always carries an unsubscribe link; transactional never does.
    if (isMarketing) {
      context.unsubscribeUrl = `${base}/u/${await mint("unsubscribe", {})}`;
    }
  }

  return {
    subject: entry.subject(context).trim(),
    html: entry.html(context),
    text: entry.text(context),
  };
}
